language: python
python:
  - "3.8"
services: docker

before_install:
  - sudo apt-get update
cache: pip

install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - flake8 src/Index.py

after_success:
