language: python
python:
  - "3.8"
services: docker

before_install:
  - sudo apt-get update
cache: pip

install:
  - pip install -r requirements.txt
  - pip install -e .
script:
  - flake8 src/Index.py

after_success:
  - git config --global user.name "georgi768"
  - git config --global user.email "goskate004@gmail.com"
  - git remote rm origin
  - git add .
  - git commit -m "Testing"
  - git remote add origin https://${GH_TOKEN}@github.com/Georgi768/TravisValidation.git
  - git push -u origin main